### ISSUE TITLE
The mod isn't working in multiplayer

### ISSUE THREAD

**Issue by Insecticon** [SChinchi/TricornEliteEquipment#2]
I did a run with a couple of friends of mine, but the tricorn wouldn't target elite enemies. Even when the host tried to use it himself in the run, it still wouldn't work. It only seems to work in singleplayer, even when every client has the mod installed.

**Comment by SChinchi** [comment]
The mod has been tested in multiplayer, so something more must be going on. Do you by any chance have the `ItemBlacklist` mod? There is an incompatibility with it.

Otherwise, I would need a log to investigate it further.

**Comment by Insecticon** [comment]
Yeah, were using itemblacklist. None of us realized that it was incompatible with this mod.

**Comment by Thresh90** [comment]
> The mod has been tested in multiplayer, so something more must be going on. Do you by any chance have the `ItemBlacklist` mod? There is an incompatibility with it.
> 
> Otherwise, I would need a log to investigate it further.

So I got confirmation from Moffein that the ItemBlacklist mod seems to have code messing with Tricorn in specific, so it can't be this mod's fault. If anything i'd probably take it up with Thrayonlosa

**Comment by SChinchi** [comment]
I am already aware of the exact issue, I had just opted to mark this mod incompatible with ItemBlacklist and it was set so it wouldn't load in its presence. This has been noted both in the changelog and logged in the console.

Circumventing the incompatibility isn't a difficult thing and I might just do that, since the incompatibility has been brought to my attention more times since the initial fix, which implies the presence of both mods is popular enough to act on it and the existence of the incompatibility doesn't seem to be readily known to the wider userbase.

**Comment by SChinchi** [comment]
Duplicate of #1
